export const routes = {
  home: "/",
  login: "/login",
  register: "/register",
  posts: "/posts",
  post: "/posts/:postId",
  userPosts: '/my-posts',
  account: "/account",
  createPost: "/create-post",
  editPost: "/edit-post/:postId",
  users: "/users",
  questions: "/questions",
  createQuestion: "/create-question",
  notFound: "*",
};
